/*
 * Brave Data Events API
 * Brave Data Events is an API that simulates event logging from mobile devices and web applications for analytical data processing. The client can track the status of the data with the corresponding ID via GET endpoint.<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2020-10/circulo_de_credito-apihub.png' height='40' width='220'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.brave.dataevents.client.model;

import java.util.Objects;
import 
com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Upload dataset information.
 */
@Schema(description = "Upload dataset information.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-28T21:38:54.271769326Z[GMT]")

public class UploadDataModel {
  @SerializedName("dataId")
  private String dataId = null;

  @SerializedName("data")
  private String data = null;

  public UploadDataModel dataId(String dataId) {
    this.dataId = dataId;
    return this;
  }

   /**
   * The parameter which could be used to identify the dataset. We recommend using \&quot;web\&quot; or \&quot;android\&quot; or \&quot;ios\&quot; (depending on device from request is sent) followed by dash \&quot;-\&quot; and one UUID for this field.
   * @return dataId
  **/
  @Schema(example = "web-570e8420-e29b-41d4-a436-126610440900", required = true, description = "The parameter which could be used to identify the dataset. We recommend using \"web\" or \"android\" or \"ios\" (depending on device from request is sent) followed by dash \"-\" and one UUID for this field.")
  public String getDataId() {
    return dataId;
  }

  public void setDataId(String dataId) {
    this.dataId = dataId;
  }

  public UploadDataModel data(String data) {
    this.data = data;
    return this;
  }

   /**
   * The mobile dataset collected by SDK.
   * @return data
  **/
  @Schema(example = "H4sIAAAAAAAAAOVc62/bNhC/D/5DjHz...", required = true, description = "The mobile dataset collected by SDK.")
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UploadDataModel uploadDataModel = (UploadDataModel) o;
    return Objects.equals(this.dataId, uploadDataModel.dataId) &&
        Objects.equals(this.data, uploadDataModel.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataId, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UploadDataModel {\n");
    
    sb.append("    dataId: ").append(toIndentedString(dataId)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
